### ISSUE TITLE
Replacing assets instead of deleting and re-uploading

### ISSUE THREAD

**Issue by zuendi123** [Screenly/screenly-ose#1123]
It would be nice if there was a possibility for replacing an asset instead of deleting and re-uploading it.
The replacement would apply all the settings like duration, start-date and end-date but only replace the asset.

**Comment by vpetersson** [comment]
@zuendi123 The reason for this largely being that that there are a number of checks done when an asset is added. That's why you cannot modify an asset (other than the meta data). Happy to accept a pull request for this that takes all those checks into account but unless there is a really strong demand for this, we won't be able to allocate resources.
