### ISSUE TITLE
Browser outdated for Google Maps

### ISSUE THREAD

**Issue by Jeff-lansidel** [Screenly/screenly-ose#1236]
This URL

https://www.google.com/maps/@47.7464122,-116.8132666,22667m/data=!3m1!1e3!5m1!1e1

Production, Development and Experimental all are stating the browser needs to be updated on a Raspberry Pi 3 b+

![20191004_212148](https://user-images.githubusercontent.com/40490812/66249798-bcc25200-e6ed-11e9-9197-211a4d7b6660.jpg)

I used the bash <(curl -sL https://www.screenly.io/install-ose.sh) command to change between the different environments with the same result.  Is there a way to use Firefox or Chrome browser with OSE?

Thanks, Jeff

**Comment by vpetersson** [comment]
No, it's not possible to use Chrome or Firefox, as they don't have the remote access capabilities that we're using (to display the desired assets).

While the browser used in the development and stable version is dated (uzbl), the experimental version should address that. There might be some setting required in the compilation options in order to get Maps to work.
