### ISSUE TITLE
howto create wifi hotspot on Screenly OSE and raspberry ?

### ISSUE THREAD

**Issue by youbloub** [Screenly/screenly-ose#1263]
Hi,
I would like that my raspberry/Screenly was a server/hotspot wifi.
So I can connect localy with any laptop and modify assets.

how to do this ? Can I do this ?

**Comment by vpetersson** [comment]
While we do have support for hotspot for *configuring* WiFi, it's different than what you're asking for. The problem is that the Raspberry Pi doesn't have an [RTC](https://en.wikipedia.org/wiki/Real-time_clock), so it *needs* an internet connection to know what time it is (which is paramount for Screenly to operate). This is not Screenly specific of course.
