### ISSUE TITLE
Raspberry Pi still to weak to View Live-YouTube Camera streams?

### ISSUE THREAD

**Issue by hostheimer** [Screenly/screenly-ose#1276]
#### Overview of the Issue

More and more camera's viewing live streams via YouTube.
For example: https://www.youtube.com/watch?v=CByh5BIdgik

Is Screenly/Raspberry Pi 3B still  not able to view this is the performance of the newer Raspberry PI's still to low?
Is there maybe a work arround to view this kind of video streams?

#### Reproduction Steps

n/a

### Environment

* Screenly OSE Version: Sprint 10

**Comment by vpetersson** [comment]
I don't think that's supported, unless YouTube produces a pure h264 (or h265 for pi4) video feed.

**Comment by ealmonte32** [comment]
@hostheimer The RPI does seem to support it, see screenshot below, the problem is most likely the browser, I tested using the chromium-browser and RPi Model 3B+ Revision: 1.3:

Same pi running screenly, but for test environment I simply stop the screenly service and run the chromium-browser from terminal..

![image](https://user-images.githubusercontent.com/24350198/72459984-efbebc00-3799-11ea-8faa-11b12b1c418c.png)

**Comment by ealmonte32** [comment]
@vpetersson  I forgot to say, I am running into the character encoding issue? for youtube videos:

![image](https://user-images.githubusercontent.com/24350198/72460317-92773a80-379a-11ea-9164-99a5ce2f7a26.png)

**Comment by vpetersson** [comment]
Judging by the screenshot, that's a live stream. That will not work. We can only download non-streams (for obvious reasons). The only live streams that we can support are RTSP feeds (see [here](https://www.screenly.io/blog/2017/07/05/screenly-ose-0-10-is-out/)). To my knowledge, YouTube does not support this format.
