### ISSUE TITLE
readme link dead 

### ISSUE THREAD

**Issue by xhozt** [Screenly/screenly-ose#1280]
link to faq in Readme is dead https://support.screenly.io/hc/en-us/sections/202652366-Frequently-Asked-Questions-FAQ-

**Comment by vpetersson** [comment]
This is a known issue. We're overhauling the FAQ section.

**Comment by jeff-knurek** [comment]
the links to the 
* Live Demo
* QA Checklist
* API Docs

are also "dead"

**Comment by vpetersson** [comment]
* The Live Demo is a known issue. Basically the refactoring to the Docker model broke it (#1251).
* The QA Checklist appears to be broken due to the service used [Forgett](https://www.forgett.com/) has either been shut down or they have forgot to fix their SSL certificate
* API docs is a function of the demo site. It's easy to work around this, as the API docs is also exposed on any local instance of Screenly OSE.

**Comment by jeff-knurek** [comment]
* it seems like the FAQ link should be updated to: https://support.screenly.io/hc/en-us/categories/360002614653-FAQs
* yeah, QA Checklist location is obsolete - not sure if there's an alternative: https://twitter.com/rbstrachan/status/1136747590702252032/photo/1
* it looks like the API docs should point here: https://developer.screenlyapp.com/

**Comment by Eric-Screenly** [comment]
Hi @jeff-knurek , the links that you posted directly above for the FAQ and API docs are actually for our commercial (Screenly Pro) subscription platform, and not related to OSE. I just wanted to be clear so there wasn't any confusion here.

Thank you!
