### ISSUE TITLE
(Recurring) 502 Bad Gateway - nginx

### ISSUE THREAD

**Issue by swebervna** [Screenly/screenly-ose#1365]
**UPDATE:**
I found what was causing the gateway error! I tried manually running the server.py script in the screenly folder and I noticed it had an error:
![image](https://user-images.githubusercontent.com/66483494/93914737-f44a5580-fcd4-11ea-8f80-f534df9a5f22.png)

So I installed psutil again using pip install psutil

Once that installed, I ran the py script again and ALL IS WELL. Hmm, psutil must've gotten removed somehow? Possibly something to do with this?
image.png
![image](https://user-images.githubusercontent.com/66483494/93914775-02987180-fcd5-11ea-9d33-aaef3bd73c37.png)

Anyways, at least I know what it is now. I believe this should still be looked into, though. Not sure if this is happening to anybody else?

**Overview of the Issue:**
My Screenly OSE instances keep encountering this issue around a week after installing Screenly OSE. For the longest time everything worked, but lately, this issue keeps popping up, even after countless reinstallations of Screenly OSE (I install via the disk image, onto my 2 Raspberry Pi's). Screenly OSE is working just fine, it's just the web interface that I can't access.

Here's what I get when I try accessing the web interface:
![image](https://user-images.githubusercontent.com/66483494/93896018-6bc0ba80-fcbe-11ea-914b-d7554e208a7e.png)

Reproduction Steps:
Very simple for my case: start the Raspberry Pi. Nothing specific from my input causes it, it's just stuck anytime the Pi runs.

What I've tried:

- Formatting Pi SD cards and flashing the disk image again (multiple times) to install
- Updating Screenly OSE (every time I update, I get this error & block of code in the middle of the update process):
sudo -u pi ansible localhost -m git -a 'repo=https://github.com/screenly/screenly-ose.git dest=/home/pi/screenly version=production'
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '.'
localhost | FAILED! => {
"msg": "Unexpected failure during module execution.",
"stdout": ""
}

**Environment:**
Raspberry Pi Hardware Version: Model 3B Revision: 1.2 Ram: 1 GB Sony UK
Raspberry Pi Network Setup: Ethernet
Screenly OSE Version: master@fcf603e

**Comment by ealmonte32** [comment]
@swebervna 
if you take a look at the current requirements file here https://github.com/Screenly/screenly-ose/blob/master/requirements/requirements.txt#:~:text=psutil

you can see that psutil is called upon to be installed by the ansible task, so i am pretty sure you are running into something that almost no one else is running into.. 
if you run the install script and select master branch, you should be able to get screenly-ose running normally.. although some changes are pending in pull requests, you should still be able to not get that bad gateway error, not really sure how you got it in the first place since like i mentioned psutil is part of the requirements..

**Comment by swebervna** [comment]
> @swebervna
> if you take a look at the current requirements file here https://github.com/Screenly/screenly-ose/blob/master/requirements/requirements.txt#:~:text=psutil
> 
> you can see that psutil is called upon to be installed by the ansible task, so i am pretty sure you are running into something that almost no one else is running into..
> if you run the install script and select master branch, you should be able to get screenly-ose running normally.. although some changes are pending in pull requests, you should still be able to not get that bad gateway error, not really sure how you got it in the first place since like i mentioned psutil is part of the requirements..

It's beyond me why I'm encountering this. I have two Raspberry Pi's and they both experience this issue after a day or two of running a fresh install of Screenly-OSE. Also, our Pi's worked for years and it was earlier this year that this started happening. My guess is some sort of incompatibility and somehow that's causing psutil to uninstall?

**Comment by ealmonte32** [comment]
> It's beyond me why I'm encountering this. I have two Raspberry Pi's and they both experience this issue after a day or two of running a fresh install of Screenly-OSE. Also, our Pi's worked for years and it was earlier this year that this started happening. My guess is some sort of incompatibility and somehow that's causing psutil to uninstall?

I am not sure either but this is why I usually recommend using the bash install script on a fresh [raspbian stretch lite or buster lite image](http://downloads.raspberrypi.org/raspbian_lite/images/?C=M;O=D), that way you are for sure getting the latest installation because remember any image released with packaged software becomes outdated within days already because you can never test everything before releasing it.
