### ISSUE TITLE
RPi3 with experimental branch issues

### ISSUE THREAD

**Issue by Kipjr** [Screenly/screenly-ose#1384]
#1366 after test mentioned there I found the following:

#### Overview of the Issue

Several issues occur while installing Experimental branch on Raspi 3 Buster. 

- Logfiles nowhere to be found. Even after enable and reboot. Nothing in /var/log  or in /tmp

- Missing default assets. Where is the clock?

- Modern HTML not supported such as Canvas. Try to display a gauge in GSheets for example.

- unable to get in SSH from console with ctrl alt f1

#### Reproduction Steps

- Install Raspberry Pi OS Buster 32 Bit lite

- install.sh with experimental branch

#### Environment

* Raspberry Pi Hardware Version: 3B
* Raspberry Pi Network Setup: Wired, DHCP
* Screenly OSE Version: Experimental via Install-ose.sh

Is the version below the correct version of Screenly-OSE?
![image](https://user-images.githubusercontent.com/12066560/96385343-8b4ee400-1193-11eb-883b-b7a6f3e92328.png)

**Comment by vpetersson** [comment]
> Logfiles nowhere to be found. Even after enable and reboot. Nothing in /var/log or in /tmp

You mean log files for Screenly? If so, that is expected as it is logging in Docker. `docker logs <container>` should show the logs.

> Missing default assets. Where is the clock?

This is actually done as part of the image builder, rather than in the installation. 

> Modern HTML not supported such as Canvas. Try to display a gauge in GSheets for example.

Yeah, I'm sure that there are lots of things that won't work yet. However, we are in much better control of our own destiny with this new browser and are able to enable features.

> unable to get in SSH from console with ctrl alt f1

This is expected. Since frame buffer takes over the display, you won't be able to login using the console. You need to [SSH into the device](https://www.raspberrypi.org/documentation/remote-access/ssh/).
