### ISSUE TITLE
Feature Request: Install custom SSL certificate

### ISSUE THREAD

**Issue by swebervna** [Screenly/screenly-ose#1513]
This is a pretty simple request - I'd like to be able to install an issued SSL certificate for our Screenly instances so our users don't have to deal with Chrome's warning page for insecure connections.

Thank you! :)

**Comment by ealmonte32** [comment]
I believe you might have to install the certificate and key onto the nginx image/docker, and configure the info on the file: https://github.com/Screenly/screenly-ose/blob/master/docker/nginx/nginx.conf

Because this is what chrome will be reading from as the web server.
[This might be helpful](https://www.digicert.com/kb/csr-ssl-installation/nginx-openssl.htm) after you have the SSL ready and in place. I would test it first before rebuilding the whole docker image of nginx, just shell into the docker and make the changes and restarting of such.
