### ISSUE TITLE
Base OS-Packages should not be removed for no reason (i.e. dphys-swapfile)

### ISSUE THREAD

**Issue by oxivanisher** [Screenly/screenly-ose#1664]
The `dphys-swapfile` package is installed by default on raspbian systems. The removal makes no sense to me, since its not used anywhere by screenly or conflicts to anything I found with screenly. If this is only a "cleanup" task for old deployments, it should be handled differently IMHO.

https://github.com/Screenly/screenly-ose/blob/20b040a7791c0c898a7360f4cd3a22ceac5206b3/ansible/roles/system/tasks/main.yml#L200

I found this because a default ansible role of mine which configures swap failed, because the systemd unit `dphys-swapfile.service` is masked due to the removal of the `dphys-swapfile` package. At least it should be documented somewhere that it gets removed and why, so the search trough the source code is not the only way to find out why this service is not working like on a default raspbian install.

**Comment by vpetersson** [comment]
The removal of swap is intentional. This code was written some time ago, so it is possible that things have changed.

Our position is that swap should never be enabled on a device running on an SD card, as it massively reduces the lifespan of the SD card. Even with an industrial grade SD card, it radically decreases the life span as it. This is why we have swap disabled on our commercial deployments as well. 

Now, the code might need to be updated, but not the core philosophy behind it.

**Comment by ealmonte32** [comment]
@oxivanisher 
It is actually a good thing that screenly OSE disables and removes swap, as viktor mentions, you are the exception and not the rule, there's a lot of users who ask how they can help reduce wear on their SD card, and besides swap off, I tell them to disable journaling on their ext4 partition since that is the top disk writing process when running a fresh install of raspbian lite with screenly OSE, or if you need logs to just set `journald.conf to Storage=volatile` and install `zram` if you really need to use more memory rather than using the default swap disk.

**Comment by oxivanisher** [comment]
As I said, I get that and see the problem. But it is nowhere documented or mentioned. And instead of removing a package that is installed by the OS, it would be very easy to just disable the service with ansible.
If you want, I can create a PR with a ansible solution where it would disable the dphys-swapfile.service but add a variable that can be set to skip this step.

**Comment by ealmonte32** [comment]
> As I said, I get that and see the problem. But it is nowhere documented or mentioned. And instead of removing a package that is installed by the OS, it would be very easy to just disable the service with ansible.

Documented? I know you have good intentions, but sorry I dont agree we should document every step the process of screenly OSE installation takes besides the current way it is in the ansible playbook in the document i tried to make a long time ago detailing most of the files and services but it is too much upkeep since theres many changes to the project, thus if you wanted to see everything ansible does you would have to dive into the playbook tasks, again, this is not normal for someone that wants to simply use screenly OSE, whereas someone more tech savvy as yourself can notice those things and if you decide to use it then you can customize your screenly installation like changing the removal to disabled instead or leaving it on, etc, which again i want to stress this, the raspberry pi is being used for screenly OSE, thus this is how it comes and for a reason, if you decide you need to do other things with it like adding your own ansible stuff or other packages, you are then doing something out of the scope of the original screenly project, which is perfectly fine.
Also, if you want to create a document detailing every step the ansible playbook does, I would gladly give it a thumbs up since it would help the rare number of users who need to know everything screenly OSE installation does.


>If you want, I can create a PR with a ansible solution where it would disable the dphys-swapfile.service but add a variable that can be set to skip this step.

The little issue I have with this is that it then introduces an extra step in the installation script like asking users if they want to disable swap or not, which not many users even know what that is, thus going back to the original reason that if someone needs swap then they can simply install it themselves afterwards.

**Comment by oxivanisher** [comment]
> Documented? I know you have good intentions, but sorry I dont agree we should document every step the process of screenly OSE installation takes besides the current way it is in the ansible playbook in the document i tried to make a long time ago detailing most of the files and services but it is too much upkeep since theres many changes to the project, thus if you wanted to see everything ansible does you would have to dive into the playbook tasks, again, this is not normal for someone that wants to simply use screenly OSE, whereas someone more tech savvy as yourself can notice those things and if you decide to use it then you can customize your screenly installation like changing the removal to disabled instead or leaving it on, etc, which again i want to stress this, the raspberry pi is being used for screenly OSE, thus this is how it comes and for a reason, if you decide you need to do other things with it like adding your own ansible stuff or other packages, you are then doing something out of the scope of the original screenly project, which is perfectly fine. Also, if you want to create a document detailing every step the ansible playbook does, I would gladly give it a thumbs up since it would help the rare number of users who need to know everything screenly OSE installation does.

OK, I get that.

> The little issue I have with this is that it then introduces an extra step in the installation script like asking users if they want to disable swap or not, which not many users even know what that is, thus going back to the original reason that if someone needs swap then they can simply install it themselves afterwards.

No, it is surely not the idea to ask the user. My idea would be that the installation works exactly as before but tech savvy users can override a variable so that their setups can be idempotent.

**Comment by ealmonte32** [comment]
@oxivanisher I looked at the PR and my honest opinion is that look at all the extra code you are introducing to a non-problem, and i cannot honestly see any advanced users needing this since the use cases for extra arguments within the use of screenly OSE are so limited, that it doesn't make sense to introduce this as an option when tech savvy users can do it themselves when and if they needed to which i don't see any use cases, especially something as simple as dphys package.

>Also: I think it is better to disable and mask the dphys-swapfile service. If it only gets removed, its always possible that a upgrade will re-install the package, since it is a Raspbian base OS package. If a service gets disabled by a user (in this case the screenly ose setup), it will remain even if a update is installed.

the point of delivering screenly OSE as it currently is and with all the packages we remove, is for a reason and if a user starts installing extra packages or other packages that will then need dphys installed or whatever, is again outside of the scope of this and the personal choice of that user.

I think your skills could be used better in finding more unnecessary packages to remove rather than leaving them on the system, one of the goals for screenly OSE is for it to be lean and lightweight, so that would be something i would support, but not this, sorry mate.

**Comment by oxivanisher** [comment]
> @oxivanisher I looked at the PR and my honest opinion is that look at all the extra code you are introducing to a non-problem, and i cannot honestly see any advanced users needing this since the use cases for extra arguments within the use of screenly OSE are so limited, that it doesn't make sense to introduce this as an option when tech savvy users can do it themselves when and if they needed to which i don't see any use cases, especially something as simple as dphys package.
> 
> the point of delivering screenly OSE as it currently is and with all the packages we remove, is for a reason and if a user starts installing extra packages or other packages that will then need dphys installed or whatever, is again outside of the scope of this and the personal choice of that user.
> 
> I think your skills could be used better in finding more unnecessary packages to remove rather than leaving them on the system, one of the goals for screenly OSE is for it to be lean and lightweight, so that would be something i would support, but not this, sorry mate.
> 

No worries. As I said, I can easily remove my PR, I wrote that in less than an hour. If I spot packages that can be removed, I will let you know. 👍 

> By the way, I really like this thing you made: https://oxi.ch/wp-content/uploads/2021/11/20211119_172436-scaled.jpg

Thanks :)
