### ISSUE TITLE
suspend display during off-hours

### ISSUE THREAD

**Issue by axel-b** [Screenly/screenly-ose#26]
[I'm using this issue to document what I found in [a topic on the raspberrypi forum](http://www.raspberrypi.org/phpBB3/viewtopic.php?f=64&t=7570) ]

Our Screenly-controlled display is in the office; it seems a waste to have it always on, also at night and during the weekends when there is noone there.
[I don't care (yet?) about suspending/resuming the Raspberry Pi, but I guess that could be done too.]

To switch off display, programmatically, on raspberry pi:

```
/opt/vc/bin/tvservice -p; /opt/vc/bin/tvservice -o
```

To switch the display on again (the chvt command combination re-activates X Windows):

```
/opt/vc/bin/tvservice -p ; sudo chvt 6; sudo chvt 7
```

I use the following crontab entry, to switch the display off after working hours, and to switch it on in the morning, on working days.

```
# minute   hour   day of month     month   day of week       command
#  0-59    0-23   1-31             1-12    0-7 (0/7 is Sun) 
30         18     *                *       *                 /opt/vc/bin/tvservice -p ; /opt/vc/bin/tvservice -o
30         8      *                *       1-5               /opt/vc/bin/tvservice -p ; sudo chvt 6; sudo chvt 7
```

**Comment by waterloomatt** [comment]
This solution works well for me and my setup is running through a HDMI/VGA converter.

**Comment by vpetersson** [comment]
We might introduce this as an experimental/beta in Sprint 3 feature to see how it goes.

It will however require both front-end and back-end work.

**Comment by C-Duv** [comment]
+1 to add an *Power management* asset type so that we can use the "Schedule Overview" page to sleep/resume the monitor at given scheduled moments.

@axel-b thanks for giving the `chvt` tip: exactly what I was looking for (my screen stayed black after resuming the HDMI).

**Comment by ersan** [comment]
+1 would also love this.

**Comment by FeuerwehrCloud** [comment]
better as chvt is

**Comment by C-Duv** [comment]
Using `fbset -depth 8; fbset -depth 16; xrefresh` to refesh the display gets me:

> X11 connection rejected because of wrong authentication.
> xrefresh:  unable to open display 'localhost:10.0'

**Comment by vpetersson** [comment]
I've created #585 to get better status of this. I've also written an [article on the topic](https://news.screenly.io/how-to-automatically-turn-off-and-on-your-monitor-from-your-raspberry-pi-5f259f40cae5?source=collection_home---4------0-----------). 

I'd love to get people's feedback on this to see what works and what doesn't.

**Comment by john-bonachon** [comment]
@vpetersson three questions,
1) what would happen with the Raspberry Pi in that case? 
2) in order to be sure to turn off the monitor, what if you turn off the TV monitor with the regular remote control? 
In both cases, will Screenly be still running as if there was a monitor despite there is no HDMI signal? would that shorten the SD card lifespan?

**Comment by vpetersson** [comment]
@john-bonachon 

>  what would happen with the Raspberry Pi in that case?

Not sure if I follow. It will just keeps running.

> in order to be sure to turn off the monitor, what if you turn off the TV monitor with the regular remote control?

That would in theory be more or less the same thing.

> In both cases, will Screenly be still running as if there was a monitor despite there is no HDMI signal? would that shorten the SD card lifespan?

Sure, but that's negligible IMHO. If you really want to disable assets in sync with that, you could do that using the [API](http://ose.demo.screenlyapp.com/api/docs/).

**Comment by john-bonachon** [comment]
Ok, I'm mostly concerned about the Raspberry Pi and SD card lifespan when running it 24/7 vs. turning on/off on working hours ~8am-17pm

Do you have some experiences on that?

**Comment by vpetersson** [comment]
> Ok, I'm mostly concerned about the Raspberry Pi and SD card lifespan when running it 24/7 vs. turning on/off on working hours ~8am-17pm

Turning the Raspberry Pi on and off every day is most likely causing more read/writes than just leaving it running. Hence, from that perspective, I don't think it will make much sense. Moreover, a device is far more likely to break during this process too.

> Have you considered adding a Power Off button in the Screenly interface?

it would in theory be possible to do that, but we are intending to tighten up the security so that would be something we'd do after that if so.

**Comment by john-bonachon** [comment]
`Turning the Raspberry Pi on and off every day is most likely causing more read/writes than just leaving it running. Hence, from that perspective, I don't think it will make much sense. Moreover, a device is far more likely to break during this process too.`
good point

**Comment by benurbano** [comment]
Hi,

The subject is not to do with cpu suspend like on a normal PC.

This is suspending display output/controlling TV. For example... we have 20
x TV displaying throughout large venue, The raspi will turn TV on and make
sure it TV is correct channel input at 7am, and 6pm off. No human is
required to turn TV on or off.

So with either API or using hdmi-cec, both scenarios involve live cpu, not
suspended.

Regards,
Ben



On 27 Jan. 2018 1:15 am, "john-bonachon" <notifications@github.com> wrote:

Ok, I'm mostly concerned about the Raspberry Pi and SD card lifespan when
running it 24/7 vs. turning on/off on working hours ~8am-17pm

Do you have some experiences on that?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Screenly/screenly-ose/issues/26#issuecomment-360811620>,
or mute the thread

**Comment by vpetersson** [comment]
@benurbano I wrote a [blog post](https://www.screenly.io/blog/2017/07/02/how-to-automatically-turn-off-and-on-your-monitor-from-your-raspberry-pi/) on this topic. The issue is that it is very hard to do well in my experience. With my limited sample set, I haven't found a way to do this that works consistently with power on/off across a diverse set of monitors. 

That said, it is fairly easy to add a cronjob based with the exact command that works for your monitors.
