### ISSUE TITLE
start_date cannot be less than Python's DateTime.MinYear

### ISSUE THREAD

**Issue by aolszowka** [Screenly/screenly-ose#646]
The `start_date` has a boundary condition due to the differences between SQLite's DateTime.Min (https://sqlite.org/lang_datefunc.html) and Python's DateTime.Min (https://docs.python.org/3/library/datetime.html)

There does not appear to be any asserts on the API when inserting assets.

Setting the `start_date` outside the valid range results in Screenly throwing errors.

**Why this matters**
For my use case of Screenly I intend to run it "disconnected" as a slide show for a large number of assets. Unfortunately because my Raspberry Pi (RPi 3) does not have a Real Time Clock, therefore upon every reboot the date is set to the Unix Epoch (Thursday, 1 January 1970).

Based on my (limited) understanding of Screenly's Start Date Logic (in viewer.py) logic this means that none of my assets would ever display after uploading them. Therefore I have taken to setting the start date to a point before the Unix Epoch.

The obvious solution of sqlite's DateTime.Min was not correct and I encountered this error.

**Comment by vpetersson** [comment]
I don't think the logic in SQLite vs. Python is related. The issue is that your clock is off. That's what needs to be addressed. You have a few ways to do this.

 * You could setup an NTP server on the local network and configure the time using that.
 * You could add an RTC module as you mention. These are super cheap (as in ~$10).
 * **[I really wouldn't recommend this]** You could add something to the boot process that sets the date to some predetermined timestamp.
