### ISSUE TITLE
Play Youtube as a website?

### ISSUE THREAD

**Issue by catsarecool999** [Screenly/screenly-ose#739]
I work at a public library and I'd like to play videos on our YouTube channel "as is" on Youtube.com. However, Screenly keeps pulling them as video assets, which does not pull the .srt files. I'd rather they just play as is on Youtube with the subtitles. Any advice? Right now, I have to download the videos and hardcode the subtitles which isnt very convenient.

**Comment by vpetersson** [comment]
That's unfortunately not possible today. The reason is mainly because the Raspberry Pi isn't powerful enough* to play YouTube videos. That's why we need to download them and play them through a custom video player to get full hardware acceleration. 

`*` *It is technically possible with mixed result, but not with the current setup of Screenly OSE*
