### ISSUE TITLE
webm and ogv videos are chopped and slow

### ISSUE THREAD

**Issue by jarrettrus26** [Screenly/screenly-ose#747]
When displaying a web page with <video> embedded its not playing very well. Files converted and are 1.5-2 mb. When i am looking at the same page on regular PC video works well. This web page, by the way is a wordpress that is installed on localhost of that very berry screenly pi ) Any thoughts?

**Comment by vpetersson** [comment]
This is expected behavior. There is no way to make this work using the current browser unfortunately (since it doesn't have GPU acceleration). Keep an eye on ticket #527. Before that it will not work. Also, we strongly discourage you to run anything other than Screenly on the Raspberry Pi as it is likely going to cause performance issues.
