### ISSUE TITLE
Powerpoint *.ppsx file support

### ISSUE THREAD

**Issue by s6thsense** [Screenly/screenly-ose#988]
Are there plans for Screenly OSE to be able to support powerpoint *.ppsx files?
Thanks

**Comment by willworkforicecream** [comment]
I've found that Screenly OSE handles playing Google Slides pretty well and has been more convenient than powerpoint in some cases.

**Comment by vpetersson** [comment]
@s6thsense This is unlikely something we will ever support due to the proprietary nature of PowerPoint. In short, there is not reliable way to deal with PowerPoint without using tools from Microsoft. Moving said presentations to Google Slides is likely the best workaround as @willworkforicecream suggested.
